language: node_js

node_js:
  - "13.7.0"
  
os: 
- linux

env:
  - ARCHITECTURE="$TRAVIS_OS_NAME"
  
before_script:
  - npm i -S -D 
    @babel/core 
    @babel/preset-env
    babel-loader
    clean-webpack-plugin
    css-loader
    file-loader
    html-webpack-plugin
    style-loader
    webpack
    webpack-cli
    webpack-dev-server
    webpack-merge
  
install: 
- npm i

script:
 - npm install --build-from-source
 - cd $TRAVIS_BUILD_DIR

 
